### ISSUE TITLE
Typecasting misinterpretation in TS files when React Typescript is on.

### ISSUE THREAD

**Issue by etienne-dldc** [fuse-box/fuse-box#133]
Hi,

## Some context

I have run FuseBox on a big TypeScript/React app I'm working on (just to see how hard it would be to use it instead of Webpack) and I get some `illegal token` error in certain `.ts` files.

## The problem

The problem was that we were using typecasting with `<Type> stuff` instead of the `stuff as Type` form. Since we are in `.ts` file, that should not raise an error and our current compiler does not find any error.
But when I ran FuzeBox, it raised some strange error because he was interpreting the type as a React Element, treating what follows as simple text, but then some `{` appear and everything blows up ^^.

## Probable solution

I think the solution is to try to enable JSX only on `.tsx` files and not `.ts`.
Since I haven't looked at the code parse files so I don't know how complicated this is...

PS: Sorry for my English :/

**Comment by nchanged** [comment]
Try creating `tsconfig.json` with [these](https://github.com/fuse-box/fuse-box-ts-react-reflux-seed/blob/master/src/tsconfig.json) properties.

**Comment by etienne-dldc** [comment]
I've replaced my `tsconfig.json` with the one you provide and get the exact same result.

Here is the error: 
```
Acorn error: Unexpected token (8:8)
File: /Users/etienne-dldc/Workspace/bitbucket.org/realyticsio/dashboard-v2/src/client/bundles/Dashboard/metric/serializer/Date48MetricSerializer.ts

6          return value ? Moment48_1.Moment48.parse(React.createElement("string", null,
7              " value, metric.getMetadata('format', null)) : null;" + " " + "}" + " " + "serializeSingle(metric: Metric, value: Moment48): MetricScalarType ",
8          ,
9              " value ? value.format(metric.getMetadata('format', null)) : null;" + " " + "}" + " " + "matches(metric: Metric): number ",
10          ,
11              " ('date_48' === metric.getType().getValueType()) ",
12          ,
```

To fix the error I have to replace a typecasting which is way before in the code : `<string> value` by `value as string` and the error is gone.

The thing is that with `tl-loader` I don't get the error and after looking at both code I think the différence is that `ts-loader` passes `filesname` in options to `transpileModule` while FuseBox don't, and TypeScript uses `filename` to detect if it's a `.ts` or a `.tsx` file and if `<stuff>` should be interpreted as a component or as typecasting.

So I guess that if `WorkFlowContext -> getTypeScriptConfig` return the filename in the config it should fix the error :)

**Comment by nchanged** [comment]
`v1.3.110` should fix it. Please verify

**Comment by etienne-dldc** [comment]
Nope, I still get the error.

Here is a reproduction of it : https://github.com/etienne-dldc/fuse-box-ts-react-reflux-seed

**Comment by devmondo** [comment]
@etienne-dldc did you clear `.fusebox` cache folder after update?

**Comment by nchanged** [comment]
I will check it tomorrow, if nothing helps.

**Comment by etienne-dldc** [comment]
@devmondo For my project : yes. For the reproduction it's a clean fork of `fuse-box-ts-react-reflux-seed` so fusebox was installed with version `v1.3.112`.

**Comment by devmondo** [comment]
try latest and let us know if it does not work still.

we will close this for now, but feel free to open it otherwise :)
