### ISSUE TITLE
CSS Plugin emits raw CSS code into bundle and fails the startup process

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#295]
Hi, I am not sure why CSS plugin keeps inserting the raw css code into the bundle.

I am getting following error:

```
/Users/tomi/Downloads/wallaby-1035-master/node_modules/rc-collapse/assets/index.css:1
(function (exports, require, module, __filename, __dirname) { .rc-collapse {
                                                              ^
SyntaxError: Unexpected token .
```

One of the packages I am using imports css as

```
import 'rc-collapse/assets/index.css'
```

Following is my config:

```js
const rootFolder = 'build/luis';
const fsbx = require('fuse-box');
const StubPlugin = require('proxyrequire').FuseBoxStubPlugin(/[^(index.tsx)]/);

fsbx.FuseBox.init({
  homeDir: "src",
  log: false,
  sourceMap: {
    bundleReference: 'app.js.map',
    outFile: `${rootFolder}/app.js.map`
  },
  plugins: [
    StubPlugin,
    fsbx.JSONPlugin(), [
      fsbx.CSSResourcePlugin({
        dist: `${rootFolder}/resources`,
        resolve: (file) => `/resources/${file}`
      }),
      fsbx.CSSPlugin({
        outFile: (file) => `${rootFolder}/${file}`
      })
    ]
  ],
  outFile: `${rootFolder}/app.js`,
}).devServer("> index.tsx", {
  root: rootFolder,
  port: 3000
});
```

**Comment by nchanged** [comment]
Can you update to the latest version? Because it has been fixed there

**Comment by tomitrescak** [comment]
I have already modified everything to not have CSS refrences from packages, I'll reopen if the issues reapears.

**Comment by subnomo** [comment]
I'm still having this issue in FuseBox 2.2.31. It seems to only happen with arithmetic that excludes dependencies.

Here is my config:

```js
const {
  FuseBox,
  CSSPlugin,
  CSSResourcePlugin,
  CopyPlugin,
  EnvPlugin,
} = require('fuse-box');

let isProduction = process.env.NODE_ENV === 'production';

const fuse = FuseBox.init({
  homeDir: 'src/',
  output: 'dist/$name.js',
  target: 'electron',
  log: !isProduction,
  hash: false,
  cache: !isProduction,
  sourceMaps: !isProduction,
  tsConfig: 'tsconfig.json',
  shim: {
    electron: { exports: "global.require('electron')" },
  },
  plugins: [
    EnvPlugin({ ...process.env }),
    [CSSResourcePlugin(), CSSPlugin()],
  ]
});

// Bundle electron renderer code
const rendererBundle = fuse
  .bundle('renderer')
  .instructions('> [renderer/index.tsx]')
  .plugin(CopyPlugin({
      useDefault: false,
      files: ASSETS,
      dest: 'assets',
      resolve: 'assets/',
  }));
```

If I change `.instructions('> [renderer/index.tsx]')` to `.instructions('> renderer/index.tsx')`, it works as expected.

**Comment by nchanged** [comment]
Can u reproduce it in a repository?

**Comment by jaxxreal** [comment]
Hey guys, I have this issue too, but my config is super straightworfard:

"fuse-box": "^2.5.0-beta.1"

```
// fuse.ts

import { FuseBox, SassPlugin, CSSPlugin, SVGPlugin, WebIndexPlugin, JSONPlugin, CSSResourcePlugin } from 'fuse-box';

const fuse = FuseBox.init({
    homeDir: './',
    output: `./server/public/mobile/$name.js`,
    tsConfig : './client/tsconfig.json',
    plugins : [
        CSSResourcePlugin(),
        CSSPlugin(),
        SassPlugin({outputStyle: 'compressed'} as any),

        SVGPlugin(),
        JSONPlugin(),

        WebIndexPlugin({
            title: 'Project',
            path: '.'
        })
   ]
});

fuse.bundle('mobile')
    .target('browser')
    .instructions(`> client/src/js/pages/Mobile/index.tsx`);

// run bundler!
fuse.run();
```

**Comment by nchanged** [comment]
Please try fuse-box@next
And you config is wrong l, you have to chain the plugins
[
[sass,css]
]

**Comment by nchanged** [comment]
In your case
[sass, css resources, css] remember to wrap it!!! And read up on the docs, Merry Xmas

**Comment by jaxxreal** [comment]
Thanks @nchanged! Will try it! Merry Xmas you too :)

**Comment by partnerinflight** [comment]
Hm I'm still having this problem, with latest fuse-box@next. My fusebox config:

const rendererBundle = fuse
    .bundle("renderer")
    .instructions("> [app/index.tsx] +fuse-box-css")
    .plugin([LESSPlugin(lessPluginOptions), CSSPlugin()])
    .plugin(CopyPlugin({ useDefault: false, files: ASSETS, dest: "assets", resolve: "assets/" }))

Error I'm seeing:


SyntaxError: Unexpected token .
vm.js:74
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at u (/Users/eugene/personaldev/novelist/out/renderer.js:1034:1093)
