### ISSUE TITLE
Dependencies management is missing when bundling a FuseboxBundle in an other

### ISSUE THREAD

**Issue by vtabary** [fuse-box/fuse-box#457]
The magic in FuseBox is really great, and its abilities to recognize a FuseBox bundled dependency when bundling is really great so it can be optimized.

To provide a npm package, I had to bundle a library without its dependencies. You don't want to get the dependencies bundled inside your dist file in order to get the last version when you are using it.

It works great when using nodejs, but not with a browser since the ```require``` function is emulated.

The project is not bundling the dependencies of the library, and a message appears "Package xxx not found".

When debugging the bundle, the ```FuseBox.packages``` is still empty when executing the library.

You can see a sample project here : https://github.com/vtabary/sample-fusebox/tree/library/

Check the ```main.js``` dist file in ```./dist```. The library is in ```./dist/lib.js```

I'll try to dig in and find a solution. If I do, I'll send a pull request.

**Comment by nchanged** [comment]
What about create a vendor package that contains your dependencies? Load vendor first, of course.

**Comment by vtabary** [comment]
That could be a workaround. I'll give it a try.

But this means that the user is aware about all the dependencies of a library, and moreover, that the user is aware that the library is a FuseBox package, and so he has to create a vendor package manually.

If I import @angular/core for example, today, I don't have to know what are its dependencies, it's done automatically by FuseBox. 

It should be the same for a library bundled with FuseBox.

**Comment by nchanged** [comment]
@vtabary ok, what i found
1) You need to load the API first
```
<script type="text/javascript" src="https://unpkg.com/fuse-box/dist/fusebox.min.js"></script>
```

2) You packaging went wrong 
```
FuseBox.pkg("whatwg-fetch@2.0.3", {}, function(___scope___){
```
You have 2 different versions of `whatwg-fetch` in your node_modules (somewhere nested), and fusebox resolved it by setting a custom rule

```
FuseBox.pkg("project", {"whatwg-fetch":"2.0.3"}, function(___scope___){
```

So `project` knows how to load the lib, but other packages don't.

**Comment by vtabary** [comment]
1. I think that the Api is already at the end of the main.js bundle. So it shoud be ok without adding the api before, right ?

2. That's weird because when I do ```npm ls whatwg-fetch``` in my project, I only have line concerning the whatwg-fetch, and the 2 files are bundled in the same project.

I saw the "conflicting" part but I can't explain why.

I'm still digging in the fuse-box sources. The AST is ok and the ImportDeclaration plugin seems to get the correct dependencies. 

I'm inspecting now the next steps

**Comment by nchanged** [comment]
Yeah, there is something weird. FuseBox thinks that it is a conflicting library.

**Comment by nchanged** [comment]
@vtabary i think this has been fixed in `fuse-box@2.0.0-beta.8` please, verify!

**Comment by vtabary** [comment]
Great ! I'll give it a try this week.

**Comment by vtabary** [comment]
Hey, I'm back !

I tried the 2.0.0 with the same project. Still the same issue. 

I updated my repo in order to use the latest fuse-box.

**Comment by nchanged** [comment]
@vtabary it's not fixed in 2.0.0, update to the latest `2.0.11`

**Comment by vtabary** [comment]
Yep, sorry, I indeed was testing with 2.0.11 and still not working because... I was on a wrong file -_- 

But it doesn't change anything.

My external libraries from "dist/lib.js" are still not imported in my final package "dist/project.js".

I found your project : https://github.com/fuse-box/fuse-box-npm-package-seed/blob/master/fuse.js

But I didn't see anything special in it :(

**Comment by nchanged** [comment]
Have u rebundled it?

**Comment by vtabary** [comment]
Yes, I removed my dist folder and built it. 

I tried to change some configuration, but nothing changed.

**Comment by devmondo** [comment]
@vtabary i tried to clone your example, but it is incomplete for me, could you please give a full repo use case so we can investigate more and solve this issue for you ASAP :)

**Comment by vtabary** [comment]
Well, everything should be ok. 

Did you checout the library branch ?

```
$ git clone https://github.com/vtabary/sample-fusebox.git
$ git checkout library
$ npm install
$ npm run build
$ npm run start
```

And you should see something like :

```
*** project *** 
*** import whatwg-fetch =>  found
*** import lib =>  found
*** import test function =>  found
--- library ---
--- fetch =>  [object Object]
Error:  Package not found lodash.merge
*** whatwg-fetch should be the same in both files =>  false
```

**Comment by devmondo** [comment]
@vtabary I just tried your code in separate project and it works, check image below
![image](https://cloud.githubusercontent.com/assets/1266367/26737943/57c709c4-47dd-11e7-98fc-0a8d1024ed20.png)

the problem I think is with phantomjs and not FuseBox, because I get this error anyways in your project
`SetProcessDpiAwareness failed: "COM error 0x80070005  (Unknown error 0x0ffffffff80070005)"`

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
