### ISSUE TITLE
Issues with homeDir/output locations

### ISSUE THREAD

**Issue by whitecolor** [fuse-box/fuse-box#612]
First problme with `homeDir: '.'`:

```ts
const fuse = FuseBox.init({
  homeDir: '.',
  output: '../build/app.js' // I place output ouside of homeDir
})

fuse.bundle('app.js')
  .instructions(`> app.ts`)
  .hmr()
  .watch()

fuse.run({ })
```

When I change app.ts rebuild happens multiple times, not inifinit loop just multiple times:
![image](https://user-images.githubusercontent.com/736697/27198977-bd36cc9a-522d-11e7-9afa-c13799c153d9.png)

If I place `output` inside of `homeDir`, I have infinite loop.

**Comment by aretecode** [comment]
already an issue for this https://github.com/fuse-box/fuse-box/issues/488

**Comment by whitecolor** [comment]
It seem to that the problem is not only in `wathing` atleast using chokidar options I excluded (put into `ignored`) bundle files, but it still doesn't work as expected: I get module resolution error (`can not find module`).

**Comment by nchanged** [comment]
#1421

**Comment by nchanged** [comment]
#1425

**Comment by nchanged** [comment]
FIxed in `3.7.0-next.1`

**Comment by cptnhaddock** [comment]
I just tested the fix with build 3.7.0-next.7 and I still see the problem. I have one easy setup where one change triggers 13 builds. And I have one more complex project where a change triggers infinite builds. 

It is not exactly as described above. Instead the setup for both project is that homeDir is `../` and output is `./dist`. So it is still related to homeDir and output.

**Comment by nchanged** [comment]
@cptnhaddock and your platform is? OSX? Window?

**Comment by cptnhaddock** [comment]
This is a simplyfied structure of my project. It is a monorepo and contains multiple webapps with a shared common folder in the root. No magic with yarn workspaces or the like... yet. 

    .
    ├── common             # Common code shared by the webapps below and contains Vue components, images, libs and css
    ├── webapp1            # First webapp
        ├── components     # Vue components
        ├── dist           # Output from fuse build
        ├── node_modules    
        ├── views          # Vue components/views
        ├── App.vue        # Entry point for the Vue app
        ├── fuse.js        # The fuse build file :)
        ├── index.html     # index.html copied to dist
        ├── main.js        # entry point
        └── package.json
    ├── webapp2            # Second webapp with same structure as webapp1

homeDir is set to the top root, `../.`
 

I used this project and restructured it to match the above structure, and was able to reproduce the issue: https://github.com/fuse-box/fuse-box-vue-seed

I can reproduce it either by changing a css in the top common folder or something in the components folder.

**Comment by nchanged** [comment]
@cptnhaddock I've made the exact same structure, And it works as expected. Attaching a working project based on the example above.
[multi.zip](https://github.com/fuse-box/fuse-box/files/2572267/multi.zip)

**Comment by cptnhaddock** [comment]
@nchanged Thanks for looking into this issue! But I can still reproduce it with your project. I have added package.json so that you will have exactly what I have. Just do a npm install and node fuse. :)

When I change the text in SharedModule it just builds infinitely.

[multi_updated.zip](https://github.com/fuse-box/fuse-box/files/2573403/multi_updated.zip)

**Comment by nchanged** [comment]
@cptnhaddock sorry it took a while, Been very busy. It has been fixed.
